# Site settings
title: Arun Raj's Resume 
description: Arun's CV
favicon: /assets/img/avatar.JPG
baseurl: http://arunraj.xyz/resumecard
url: http://arunraj.xyz/resumecard
rss_url: /pages/atom.xml

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Arun Raj
  title: Interaction Developer
  address: Cochin, India
  email: mail@arunraj.xyz
  link: http://arunraj.xyz
  weibo:
  github: arun619
  linkedin: arun-raj-28239a34
  twitter: _raj9
  gavatar: /resumecard/assets/img/avatar.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: IdentityMine Software Solutions (India) Limited
      location: Cochin, India
      title: Software Developer
      started: 2014
      duration: (2014 - Present)
      description:
    
  educationHistory:
    - education1:
      organization: Model Engineering College, Cochin
      location: Cochin, India
      degree: Bachelor
      major: Electronics and Communications Engineering
      started: 2010
      duration: (2010 - 2014)
      description: 
  languages:
    - language1:
      name: Malayalam
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: C#.Net
      percentage: 80%
    - skill2:
      name: PhotoShop
      percentage: 60%
    - skill3:
      name: Unity 3D
      percentage: 60%
    - skill4:
      name: XAML
      percentage: 90%
    - skill5:
      name: WPF
      percentage: 90%
    - skill6:
      name: Android UI
      percentage: 60%
    - skill7:
      name: XBox 360 Apps
      percentage: 80%